apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysampleapplication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydata
  
  template:
    metadata:
      labels:
        app: mydata
  
      
    spec:
    
      
      serviceAccountName: default
      automountServiceAccountToken: false 
      containers:
      - image: nginx
        name: mydata
        securityContext:
          
          runAsNonRoot: true
          runAsUser: 10000
         
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: index-html
          mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
      
      volumes:
      - name: index-html
        configMap:
          name: mydata-cm-v1
          #serviceAccountName: mydata
---                
#################################################
# ConfigMap for index.html for mydata v1
#################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: mydata-cm-v1
data:
  index.html: |
      <!DOCTYPE html>
      <html>
      <head>
      <title>Page Title</title>
      <style>
         body {
          background-color: black;
            text-align: center;
              color: white;
            }
            </style>
            </head>
            <body>

            <h1>Kubernetes Squad !!</h1>
            <h3>This is my Demo application </h3>
      <img src="http://45.media.tumblr.com/30a0796a89045b4880dfee2387ad6aa3/tumblr_o2zbvuvChc1s4fz4bo1_r1_500.gif" alt="Version1" style="width:700px;height:300px;">

      </body>
      </html>
